#!/usr/bin/env php
<?php

define('PROJECT_NAME', 'command');

define('BASE_NAMESPACE', 'tpr');
define('DS',DIRECTORY_SEPARATOR);

define('ROOT_PATH', __DIR__ . DS);
define('APP_PATH', ROOT_PATH . PROJECT_NAME . DS);
define('CONF_PATH', ROOT_PATH . 'config' . DS);
define('RUNTIME_PATH', ROOT_PATH . 'runtime' . DS . PROJECT_NAME . DS);
define('APP_NAMESPACE', BASE_NAMESPACE . '\\' . PROJECT_NAME);
define('TPR_PATH', ROOT_PATH . 'vendor' . DS . 'axios' . DS . 'tpr-framework' . DS);

// 加载框架引导文件
require TPR_PATH . 'console.php';