#!/usr/bin/env php
<?php

namespace tpr;

use tpr\command\Make;

require_once __DIR__ . '/vendor/autoload.php';

const APP_NAME = 'cli';
Path::configurate([
        "command"=>"application/commands"
]);

App::default()->config([
    'name'           => APP_NAME,
    'namespace'      => 'app\\command',
    'server_options' => [
        'name'      => 'Command Tools for TPR application',
        'version'   => '1.0.0',
        'commands'  => [
            'make' => Make::class,
        ],
    ],
])->run();
