<?php
/**
 * @author: Axios
 *
 * @email: axioscros@aliyun.com
 * @blog:  http://hanxv.cn
 * @datetime: 2017/5/17 11:22
 */
namespace admin\common\controller;

use think\Controller;
use think\Request;
use think\Session;
use think\Config;
use think\Env;

class HomeBase extends Controller{
    protected $param;

    protected $user;

    protected $themes;

    protected $config;

    public function __construct(Request $request = null)
    {
        parent::__construct($request);
        $this->themes = Env::get('web.themes','default');
        $this->param = $request->param();
    }

    protected function fetch($template = '', $vars = [], $replace = [], $config = [])
    {
        $template_dir = $this->themes.":".strtolower($this->request->module()).":".strtolower($this->request->controller()).":".$template;
        $config['view_path'] = Config::get("template.view_path").$this->themes."/";
        return parent::fetch($template_dir, $vars, $replace, $config); // TODO: Change the autogenerated stub
    }

    public function _empty(){
        echo __FUNCTION__;
        return "the function not exits";
    }

    public function __destruct()
    {
        // TODO: Implement __destruct() method.
        Session::set('last_url',$this->request->url());
    }
}