<?php
/**
 * @author: Axios
 *
 * @email: axioscros@aliyun.com
 * @blog:  http://hanxv.cn
 * @datetime: 2017/5/17 11:22
 */

namespace tpr\admin\common\controller;

use tpr\admin\common\model\Menu;
use think\Controller;
use think\Request;
use think\Session;

class HomeBase extends Controller
{
    protected $themes;

    protected $config;

    protected $menu;

    public function __construct(Request $request = null)
    {
        parent::__construct($request);
        $this->themes = c('web.themes', 'default');

        $this->assign('module', $this->request->module());

        $this->assign('current_url', $this->request->path());
    }

    public function menu($all = true)
    {
        $parent_menu = Menu::model()->menus(0, $all);
        foreach ($parent_menu as &$m) {
            $m['sub'] = Menu::model()->menus($m['id'], $all);
        }
        return $parent_menu;
    }

    protected function fetch($template = '', $vars = [], $replace = [], $config = [])
    {
        $template_dir = $this->themes . ":" . strtolower($this->request->module()) . ":" . strtolower($this->request->controller()) . ":" . $template;
        $config['view_path'] = c("template.view_path") . $this->themes . "/";
        return parent::fetch($template_dir, $vars, $replace, $config); // TODO: Change the autogenerated stub
    }

    public function _empty()
    {
        echo __FUNCTION__;
        return "the function not exits";
    }

    public function __destruct()
    {
        // TODO: Implement __destruct() method.
        Session::set('last_url', $this->request->url());
    }
}